[".cache/zsh/plugins/ohmyzsh"]
    type = "archive"
    url = "https://github.com/Crandel/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/plugins/**"]
[".cache/zsh/plugins/zsh-defer"]
    type = "archive"
    url = "https://github.com/romkatv/zsh-defer/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/zsh-defer**"]
[".cache/zsh/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".cache/zsh/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".cache/zsh/plugins/history-search-multi-word"]
    type = "archive"
    url = "https://github.com/zdharma/history-search-multi-word/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

   